###
POST http://localhost:3000/api/clientes HTTP/1.1
Content-Type: application/json

{
    "email": "carreño@gmail.com",
    "password":"12345678",
    "name":"juanC",
    "Documento":"12345678",
    "tipoDocumento":"C.C"
}
###
GET http://localhost:3000/api/clientes HTTP/1.1

###
GET http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1

###
PUT http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1
Content-Type: application/json

{
    "email": "Ejemplo1@gmail.com",
    "password":"12345678",
    "name":"ejemplo2",
    "Documento":"12345678",
    "tipoDocumento":"C.C"
}

###
DELETE http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1

//request de proyectos
###
POST http://localhost:3000/api/proyectos HTTP/1.1
Content-Type: application/json

{
    "clientesid":"65f49074efd4c9390395a4de",
    "name": "Bancolombia",
    "image": "https://i0.wp.com/interlat.co/wp-content/uploads/2020/05/ban.png?fit=512%2C512&ssl=1"
}
###
GET http://localhost:3000/api/proyectos HTTP/1.1

###
GET http://localhost:3000/api/proyectos/65f885874943c5772a2030d5 HTTP/1.1

###
DELETE http://localhost:3000/api/proyectos/65f885874943c5772a2030d5 HTTP/1.1

//request observaciones
###
POST http://localhost:3000/api/observaciones HTTP/1.1
Content-Type: application/json

{
    "proyectosid":"65f8993ffbf9afb1151bdc1d",
    "name": "Bancolombia",
    "description": "Bancolombia: Líder financiero en Colombia, ofreciendo servicios bancarios integrales y soluciones innovadoras"
}

//request actividad
###
POST http://localhost:3000/api/actividades HTTP/1.1
Content-Type: application/json

{
    "proyectosid": "65f8993ffbf9afb1151bdc1d",
    "name": "Actividad 2",
    "estadoactividad": "En progreso",
    "fechainicioActividad": "2024-03-20T10:00:00Z",
    "fechafinActividad": "2024-03-25T18:00:00Z",
    "description": "Descripción de la actividad 2"
}

###
GET http://localhost:3000/api/actividades HTTP/1.1

###
GET http://localhost:3000/api/actividades/65f8a2c498e815e6285efce2 HTTP/1.1

###
PUT http://localhost:3000/api/actividades/65f8a2c498e815e6285efce2 HTTP/1.1
Content-Type: application/json

{
    "name": "Actividad actualizada",
    "estadoactividad": "Completada"
    
}

//permisosP requests
###
POST http://localhost:3000/api/permisosp
Content-Type: application/json

{
    "name": "Permiso de administrador"
}

###
GET http://localhost:3000/api/permisosp

###
GET http://localhost:3000/api/permisosp/65f9d5b160ee84400907400b

###
PUT http://localhost:3000/api/permisosp/65f9d5b160ee84400907400b
Content-Type: application/json

{
    "name": "Permiso del miembro"
}
###
DELETE http://localhost:3000/api/permisosp/65f9d5b160ee84400907400b

//request rolproyectos
###
POST http://localhost:3000/api/rolesp HTTP/1.1
Content-Type: application/json

{
    "name": "rol worker proyecto"
}

###
GET http://localhost:3000/api/rolesp HTTP/1.1

###
GET http://localhost:3000/api/rolesp/65fa5372e22cbfe365d2bbff HTTP/1.1

###
PUT http://localhost:3000/api/rolesp/65fa5372e22cbfe365d2bbff HTTP/1.1
Content-Type: application/json

{
    "name": "rol admin proyecto"
}

###
DELETE http://localhost:3000/api/rolesp/65fa5372e22cbfe365d2bbff HTTP/1.1

//permisos usuarios requests
###
POST http://localhost:3000/api/permisos HTTP/1.1
Content-Type: application/json

{
    "name": "Permiso de usuarios"
}

###
GET http://localhost:3000/api/permisos

###
GET http://localhost:3000/api/permisos/65f9d5b160ee84400907400b

###
PUT http://localhost:3000/api/permisos/65f9d5b160ee84400907400b
Content-Type: application/json

{
    "name": "Permiso de usuario"
}
###
DELETE http://localhost:3000/api/permisos/65f9d5b160ee84400907400b

//////////////////
//request roles usuarios
###
POST http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json

{
    "name": "rol visitante"
}

###
GET http://localhost:3000/api/roles HTTP/1.1

###
GET http://localhost:3000/api/roles/65fa62eedfec33ebe8e58a8f HTTP/1.1

###
PUT http://localhost:3000/api/roles/65fa62eedfec33ebe8e58a8f HTTP/1.1
Content-Type: application/json

{
    "name": "rol admin usuario "
}

###
DELETE http://localhost:3000/api/roles/65fa62eedfec33ebe8e58a8f HTTP/1.1

//usuarios request
###
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "name": "Thomas pino",
    "email": "correo@example.com",
    "password": "12345678",
    "idrol": "65fa631fdfec33ebe8e58a95",
    "estado": "activo"
}

###
GET http://localhost:3000/api/usuarios

###
GET http://localhost:3000/api/usuarios/65fa6b1c0785d9ab00b8189e

###
PUT http://localhost:3000/api/usuarios/65fa6b1c0785d9ab00b8189e
Content-Type: application/json

{
    "name": "Thomas pino montoya",
    "email": "correo@example.com"
    
}

###
DELETE  http://localhost:3000/api/usuarios/65fa6b1c0785d9ab00b8189e

//miembros proyectos request
###
POST http://localhost:3000/api/miembrosproyectos  HTTP/1.1
Content-Type: application/json

{
    "usuariosid": "65fa6c310785d9ab00b818a5",
    "proyectosid": "65f8993ffbf9afb1151bdc1d",
    "idrolp": "65fa54fae22cbfe365d2bc06"
}

###
GET http://localhost:3000/api/miembrosproyectos HTTP/1.1

###
PUT http://localhost:3000/api/miembrosproyectos/65fdc7f66dcb4bc03e5e2e23 HTTP/1.1
Content-Type: application/json

{
    "proyectosid": "65f899cffbf9afb1151bdc21"
}

###
DELETE http://localhost:3000/api/miembrosproyectos/65fdc7f66dcb4bc03e5e2e23 HTTP/1.1

//request tareas
###
POST http://localhost:3000/api/tareas HTTP/1.1
Content-Type: application/json

{
    "idactividad": "65f8a2c498e815e6285efce2",
    "idmiembroproyecto": "65fdc9026dcb4bc03e5e2e29",
    "nombretarea": "Crear mapa mental",
    "estadotarea": "Pendiente",
    "fechainicioTarea": "2024-03-22T10:00:00Z",
    "fechafinTarea": "2024-03-24T10:00:00Z",
    "description": "Hacer un mapa"
}

