###
POST http://localhost:3000/api/clientes HTTP/1.1
Content-Type: application/json

{
    "email": "carreño@gmail.com",
    "password":"12345678",
    "name":"juanC",
    "Documento":"12345678",
    "tipoDocumento":"C.C"
}
###
GET http://localhost:3000/api/clientes HTTP/1.1

###
GET http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1

###
PUT http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1
Content-Type: application/json

{
    "email": "Ejemplo1@gmail.com",
    "password":"12345678",
    "name":"ejemplo2",
    "Documento":"12345678",
    "tipoDocumento":"C.C"
}

###
DELETE http://localhost:3000/api/clientes/65f356e3cc7a6ff04427de62 HTTP/1.1

//request de proyectos
###
POST http://localhost:3000/api/proyectos HTTP/1.1
Content-Type: application/json

{
    "clientesid":"65f49074efd4c9390395a4de",
    "name": "Bancolombia",
    "image": "https://centrodepracticas.antioquia.gov.co/media/k2/items/cache/0548677e6432786dd8df61eb3aaec139_XL.jpg"
}
###
GET http://localhost:3000/api/proyectos HTTP/1.1

###
GET http://localhost:3000/api/proyectos/65f7c7b6c84f7386cc2db5c7 HTTP/1.1

###
DELETE http://localhost:3000/api/proyectos/65f883a34943c5772a2030d2 HTTP/1.1

